// One-shot initialiser for the Waline database on Neon.
//
// Creates Waline's schema and loads the comments/pageviews migrated off LeanCloud.
// The connection string is read from the environment so it never lands in the repo
// or in a chat transcript:
//
//   export DATABASE_URL='postgres://user:pass@host/db?sslmode=require'
//   node tools/waline/import.mjs
//
// Safe to inspect first with --dry-run, and refuses to run twice unless --force is
// given, so a re-run cannot silently duplicate every comment.

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { Client } from 'pg'

const SCHEMA_URL = 'https://raw.githubusercontent.com/walinejs/waline/main/assets/waline.pgsql'
const IMPORT_SQL = path.join(process.cwd(), '_leancloud_backup', 'waline_import.sql')

const dryRun = process.argv.includes('--dry-run')
const force = process.argv.includes('--force')
const printEnv = process.argv.includes('--print-env')
// Corporate networks often block outbound 5432 (or hijack the DNS for it), which
// makes a direct connection from a work machine impossible. This emits one file to
// paste into Neon's browser SQL editor instead, needing no local DB connectivity.
const emitSql = process.argv.includes('--emit-sql')

// Windows shells keep the quotes you type around a value, and pasting a connection
// string tends to bring stray whitespace or newlines with it, so normalise rather
// than failing with a bare "Invalid URL".
const url = (process.env.DATABASE_URL || '').trim().replace(/^["']|["']$/g, '').trim()
if (!url && !emitSql) {
  console.error('DATABASE_URL is not set. Export your Neon connection string first.')
  process.exit(1)
}
if (url && !/^postgres(ql)?:\/\//.test(url)) {
  console.error('DATABASE_URL does not look like a connection string.\n'
    + 'It should start with postgres:// or postgresql:// -- got: '
    + url.slice(0, 12) + '...')
  process.exit(1)
}

// The Waline server does not read a connection string: it wants discrete PG_*
// variables. Splitting the Neon URL by hand is easy to get wrong, so do it here.
if (printEnv) {
  const u = new URL(url)
  const rows = [
    ['PG_HOST', u.hostname],
    ['PG_PORT', u.port || '5432'],
    ['PG_DB', u.pathname.replace(/^\//, '')],
    ['PG_USER', decodeURIComponent(u.username)],
    ['PG_PASSWORD', decodeURIComponent(u.password)],
    ['PG_SSL', 'true'],
  ]
  console.log('# Paste these into Vercel -> Settings -> Environment Variables.')
  console.log('# PG_PASSWORD is a secret: do not paste it into a chat or commit it.')
  for (const [k, v] of rows) console.log(k + '=' + v)
  process.exit(0)
}

if (!fs.existsSync(IMPORT_SQL)) {
  console.error('Missing ' + IMPORT_SQL + '\nRun: python py_scripts/leancloud_to_waline.py --format pgsql')
  process.exit(1)
}

const data = fs.readFileSync(IMPORT_SQL, 'utf8')

console.log('fetching Waline schema...')
const res = await fetch(SCHEMA_URL)
if (!res.ok) {
  console.error('could not fetch schema: HTTP ' + res.status)
  process.exit(1)
}
const schema = await res.text()

if (emitSql) {
  const out = path.join(process.cwd(), '_leancloud_backup', 'waline_full_import.sql')
  fs.writeFileSync(out, [
    '-- Waline schema + migrated LeanCloud data, in one file.',
    '-- Paste the whole thing into the Neon SQL editor and press Run.',
    '-- Generated by tools/waline/import.mjs --emit-sql; do not edit by hand.',
    '',
    schema,
    '',
    data,
  ].join('\n'), 'utf8')
  const inserts = data.split('\n').filter(l => l.startsWith('INSERT')).length
  console.log('wrote ' + out)
  console.log('  schema  ' + schema.length + ' bytes')
  console.log('  inserts ' + inserts)
  process.exit(0)
}

// Neon requires TLS, but honour an explicit opt-out so this can be pointed at a
// plain local Postgres for testing rather than only ever at production.
const noSsl = /[?&](sslmode=disable|ssl=false)\b/.test(url)
const client = new Client({
  connectionString: url,
  ssl: noSsl ? false : { rejectUnauthorized: false },
})
await client.connect()

// Neon databases are created empty, but a retry after a partial failure would
// otherwise stack a second copy of every row on top of the first.
const existing = await client.query(`
  SELECT to_regclass('public.wl_comment') IS NOT NULL AS has_table`)
if (existing.rows[0].has_table && !force) {
  const n = await client.query('SELECT count(*)::int AS n FROM wl_comment')
  if (n.rows[0].n > 0) {
    console.error('wl_comment already holds ' + n.rows[0].n + ' rows. '
      + 'Re-running would duplicate them; pass --force if that is really what you want.')
    await client.end()
    process.exit(1)
  }
}

if (dryRun) {
  console.log('dry run: would apply schema (' + schema.length + ' bytes) '
    + 'and ' + data.split('\n').filter(l => l.startsWith('INSERT')).length + ' inserts')
  await client.end()
  process.exit(0)
}

console.log('applying schema...')
await client.query(schema)

console.log('importing data...')
await client.query(data)

const c = await client.query('SELECT count(*)::int AS n FROM wl_comment')
const r = await client.query('SELECT count(*)::int AS n FROM wl_comment WHERE pid IS NOT NULL')
const v = await client.query('SELECT count(*)::int AS n, sum(time)::int AS s FROM wl_counter')
const dangling = await client.query(`SELECT count(*)::int AS n FROM wl_comment a
  WHERE a.pid IS NOT NULL AND NOT EXISTS (SELECT 1 FROM wl_comment b WHERE b.id = a.pid)`)

console.log('\ncomments      ' + c.rows[0].n)
console.log('replies       ' + r.rows[0].n)
console.log('dangling pid  ' + dangling.rows[0].n)
console.log('pages/views   ' + v.rows[0].n + ' / ' + v.rows[0].s)

await client.end()

if (dangling.rows[0].n > 0) {
  console.error('\nreply threading is broken -- do not point the site at this database')
  process.exit(1)
}
console.log('\nOK')
